[build]
  # Comando de build optimizado
  command = "npm run build:fast"
  
  # Directorio de salida correcto para Next.js
  publish = "out"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "20"
    NODE_OPTIONS = "--max-old-space-size=2048"
    NODE_ENV = "production"
    NEXT_TELEMETRY_DISABLED = "1"
    SKIP_TYPE_CHECK = "true"

# Configuración de redirects para Next.js SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de funciones serverless (si las necesitas)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Configuración para PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Configuración de procesamiento de assets
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Variables de entorno específicas para diferentes contextos
[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://api-navi-tracker.luciano-yomayel.com"
  NEXT_PUBLIC_BACKEND_URL = "https://api-navi-tracker.luciano-yomayel.com"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://api-navi-tracker-staging.luciano-yomayel.com"
  NEXT_PUBLIC_BACKEND_URL = "https://api-navi-tracker-staging.luciano-yomayel.com"
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://api-navi-tracker-dev.luciano-yomayel.com"
  NEXT_PUBLIC_BACKEND_URL = "https://api-navi-tracker-dev.luciano-yomayel.com"
  NODE_ENV = "development" 